{{- if and .Values.ui.enabled .Values.ui.auth (and .Values.ui.auth.enabled (include "storm.ui.auth.createSecret" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storm.ui.auth.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "storm.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "storm.commonAnnotations" . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if eq .Values.ui.auth.type "simple" }}
  users: |
    {{- range .Values.ui.auth.users }}
    {{ .username }}:{{ .password }}
    {{- end }}
  {{- end }}
{{- end }}