{{- if and .Values.auth.enabled .Values.auth.kerberos.enabled .Values.auth.kerberos.keytab }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-keytab
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $principal, $keytab := .Values.auth.kerberos.keytab }}
  {{ $principal }}.keytab: {{ $keytab | b64enc | quote }}
  {{- end }}
{{- end }}