{{- include "storm.validateZookeeper" . }}
{{- if .Values.supervisor.enabled }}
{{- include "storm.supervisor.validateMemory" . }}
{{- end -}}
{{- if .Values.cluster.stormYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  storm.yaml: |
{{ .Values.cluster.stormYaml | indent 4 }}
{{- end }}
