{{- include "storm.validateZookeeper" . }}
{{- if .Values.supervisor.enabled }}
{{- include "storm.supervisor.validateMemory" . }}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  storm.yaml: |
    # Storm configuration
    
    # Zookeeper settings
    {{- if .Values.zookeeper.enabled }}
    # Using bundled Zookeeper
    storm.zookeeper.servers:
      - {{ include "storm.zookeeperHeadlessService" . }}.{{ include "common.names.namespace" . }}.svc.{{ .Values.clusterDomain }}
    {{- else }}
    # Using external Zookeeper
    storm.zookeeper.servers:
    {{- range .Values.zookeeper.external.servers }}
      - {{ . | quote }}
    {{- end }}
    {{- end }}
    
    # Additional Zookeeper configuration
    {{- if .Values.zookeeper.extraConfig }}
    {{- range $key, $value := .Values.zookeeper.extraConfig }}
    {{ $key }}: {{ $value | toJson }}
    {{- end }}
    {{- end }}
    
    # UI configuration
    {{- if .Values.ui.enabled }}
    # Map UI port from values
    {{- if .Values.ui.ports.http }}
    ui.port: {{ .Values.ui.ports.http }}
    {{- end }}
    {{- if .Values.ui.extraConfig }}
    {{- range $key, $value := .Values.ui.extraConfig }}
    {{ $key }}: {{ $value | toJson }}
    {{- end }}
    {{- end }}
    {{- end }}
    
    # Nimbus configuration
    {{- if .Values.nimbus.enabled }}
    # Set nimbus.seeds to the headless service
    nimbus.seeds:
      - {{ include "storm.nimbusSeed" . }}
    # Map Nimbus thrift port from values
    {{- if .Values.nimbus.ports.thrift }}
    nimbus.thrift.port: {{ .Values.nimbus.ports.thrift }}
    {{- end }}
    {{- if .Values.nimbus.extraConfig }}
    {{- range $key, $value := .Values.nimbus.extraConfig }}
    {{- if and (ne $key "nimbus.seeds") (ne $key "nimbus.thrift.port") }}
    {{ $key }}: {{ $value | toJson }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    
    # Supervisor configuration
    {{- if .Values.supervisor.enabled }}
    # Generate supervisor slot ports based on slotsPerSupervisor
    {{- if .Values.supervisor.slotsPerSupervisor }}
    supervisor.slots.ports:
    {{- range $i := until (int .Values.supervisor.slotsPerSupervisor) }}
      - {{ add 6700 $i }}
    {{- end }}
    {{- end }}
    
    # Auto-calculated memory settings (if in auto mode)
    {{- if eq .Values.supervisor.memoryConfig.mode "auto" }}
    {{- include "storm.supervisor.memoryConfig" $ | nindent 4 }}
    {{- end }}
    
    {{- if .Values.supervisor.extraConfig }}
    {{- range $key, $value := .Values.supervisor.extraConfig }}
    {{- if not (and (eq $.Values.supervisor.memoryConfig.mode "auto") (or (eq $key "supervisor.memory.capacity.mb") (eq $key "supervisor.cpu.capacity") (eq $key "worker.heap.memory.mb"))) }}
    {{- if ne $key "supervisor.slots.ports" }}
    {{ $key }}: {{ $value | toJson }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    
    # Cluster configuration
    {{- if .Values.cluster.enabled }}
    {{- if .Values.cluster.extraConfig }}
    {{- range $key, $value := .Values.cluster.extraConfig }}
    {{ $key }}: {{ $value | toJson }}
    {{- end }}
    {{- end }}
    {{- end }}
    
    # Common directory configurations
    {{- if or .Values.ui.logDir .Values.nimbus.logDir .Values.supervisor.logDir }}
    # Storm log directory (using the first defined value)
    storm.log.dir: {{ .Values.nimbus.logDir | default .Values.supervisor.logDir | default .Values.ui.logDir }}
    {{- end }}
    {{- if .Values.supervisor.dataDir }}
    # Storm local directory for supervisor
    storm.local.dir: {{ .Values.supervisor.dataDir }}
    {{- end }}
    
    # Legacy cluster configuration (deprecated - will be removed)
    {{- if .Values.clusterConfig }}
    {{- include "storm.renderClusterConfig" . | nindent 4 }}
    {{- end }}
    
    # Authentication configuration
    {{- if .Values.auth.enabled }}
    {{- if .Values.auth.kerberos.enabled }}
    # Kerberos authentication
    storm.thrift.transport: "org.apache.storm.security.auth.kerberos.KerberosSaslTransportPlugin"
    java.security.auth.login.config: "/etc/storm/auth/storm_jaas.conf"
    java.security.krb5.conf: "/etc/storm/auth/krb5.conf"
    storm.principal.tolocal: "org.apache.storm.security.auth.KerberosPrincipalToLocal"
    storm.zookeeper.auth.scheme: "sasl"
    storm.zookeeper.auth.payload: ""
    {{- else }}
    # Simple authentication
    storm.thrift.transport: "org.apache.storm.security.auth.SimpleTransportPlugin"
    {{- end }}
    {{- end }}
  
  cluster.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration monitorInterval="60" shutdownHook="disable">
      <properties>
        <property name="pattern">%d{yyyy-MM-dd HH:mm:ss.SSS} %c{1.} %t [%p] %msg%n</property>
      </properties>
      <appenders>
        <!-- Console appender for Kubernetes logging -->
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout charset="UTF-8">
            <pattern>${pattern}</pattern>
          </PatternLayout>
        </Console>
        
        <RollingFile name="A1"
                     fileName="${sys:storm.log.dir}/${sys:logfile.name}"
                     filePattern="${sys:storm.log.dir}/${sys:logfile.name}.%i.gz">
          <PatternLayout charset="UTF-8">
            <pattern>${pattern}</pattern>
          </PatternLayout>
          <Policies>
            <SizeBasedTriggeringPolicy size="100 MB"/>
          </Policies>
          <DefaultRolloverStrategy max="9"/>
        </RollingFile>
        
        <RollingFile name="WEB-ACCESS"
                     fileName="${sys:storm.log.dir}/access-web-${sys:daemon.name}.log"
                     filePattern="${sys:storm.log.dir}/access-web-${sys:daemon.name}.log.%i.gz">
          <PatternLayout>
            <pattern>${pattern}</pattern>
          </PatternLayout>
          <Policies>
            <SizeBasedTriggeringPolicy size="100 MB"/>
          </Policies>
          <DefaultRolloverStrategy max="9"/>
        </RollingFile>
        
        <RollingFile name="THRIFT-ACCESS"
                     fileName="${sys:storm.log.dir}/access-${sys:logfile.name}"
                     filePattern="${sys:storm.log.dir}/access-${sys:logfile.name}.%i.gz">
          <PatternLayout>
            <pattern>${pattern}</pattern>
          </PatternLayout>
          <Policies>
            <SizeBasedTriggeringPolicy size="100 MB"/>
          </Policies>
          <DefaultRolloverStrategy max="9"/>
        </RollingFile>
        
        <RollingFile name="METRICS"
                     fileName="${sys:storm.log.dir}/${sys:logfile.name}.metrics"
                     filePattern="${sys:storm.log.dir}/${sys:logfile.name}.metrics.%i.gz">
          <PatternLayout>
            <pattern>${pattern}</pattern>
          </PatternLayout>
          <Policies>
            <SizeBasedTriggeringPolicy size="2 MB"/>
          </Policies>
          <DefaultRolloverStrategy max="9"/>
        </RollingFile>
      </appenders>
      <loggers>
        <Logger name="org.apache.storm.logging.filters.AccessLoggingFilter" level="info" additivity="false">
          <AppenderRef ref="WEB-ACCESS"/>
          <AppenderRef ref="Console"/>
        </Logger>
        <Logger name="org.apache.storm.logging.ThriftAccessLogger" level="info" additivity="false">
          <AppenderRef ref="THRIFT-ACCESS"/>
          <AppenderRef ref="Console"/>
        </Logger>
        <Logger name="org.apache.storm.metric.LoggingClusterMetricsConsumer" level="info" additivity="false">
          <appender-ref ref="METRICS"/>
        </Logger>
        <root level="info">
          <appender-ref ref="A1"/>
          <appender-ref ref="Console"/>
        </root>
      </loggers>
    </configuration>
    
  worker.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration monitorInterval="60" shutdownHook="disable">
      <properties>
        <property name="pattern">%d{yyyy-MM-dd HH:mm:ss.SSS} %c{1.} %t [%p] %msg%n</property>
        <property name="patternNoTime">%msg%n</property>
        <property name="patternMetrics">%d %-8r %m%n</property>
      </properties>
      <appenders>
        <!-- Console appender for Kubernetes logging -->
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout charset="UTF-8">
            <pattern>${pattern}</pattern>
          </PatternLayout>
        </Console>
        
        <RollingFile name="A1"
                     fileName="${sys:workers.artifacts}/${sys:storm.id}/${sys:worker.port}/${sys:logfile.name}"
                     filePattern="${sys:workers.artifacts}/${sys:storm.id}/${sys:worker.port}/${sys:logfile.name}.%i.gz">
          <PatternLayout charset="UTF-8">
            <pattern>${pattern}</pattern>
          </PatternLayout>
          <Policies>
            <SizeBasedTriggeringPolicy size="100 MB"/>
          </Policies>
          <DefaultRolloverStrategy max="9"/>
        </RollingFile>
        
        <RollingFile name="STDOUT"
                     fileName="${sys:workers.artifacts}/${sys:storm.id}/${sys:worker.port}/${sys:logfile.name}.out"
                     filePattern="${sys:workers.artifacts}/${sys:storm.id}/${sys:worker.port}/${sys:logfile.name}.out.%i.gz">
          <PatternLayout>
            <pattern>${patternNoTime}</pattern>
          </PatternLayout>
          <Policies>
            <SizeBasedTriggeringPolicy size="100 MB"/>
          </Policies>
          <DefaultRolloverStrategy max="4"/>
        </RollingFile>
        
        <RollingFile name="STDERR"
                     fileName="${sys:workers.artifacts}/${sys:storm.id}/${sys:worker.port}/${sys:logfile.name}.err"
                     filePattern="${sys:workers.artifacts}/${sys:storm.id}/${sys:worker.port}/${sys:logfile.name}.err.%i.gz">
          <PatternLayout>
            <pattern>${patternNoTime}</pattern>
          </PatternLayout>
          <Policies>
            <SizeBasedTriggeringPolicy size="100 MB"/>
          </Policies>
          <DefaultRolloverStrategy max="4"/>
        </RollingFile>
        
        <RollingFile name="METRICS"
                     fileName="${sys:workers.artifacts}/${sys:storm.id}/${sys:worker.port}/${sys:logfile.name}.metrics"
                     filePattern="${sys:workers.artifacts}/${sys:storm.id}/${sys:worker.port}/${sys:logfile.name}.metrics.%i.gz">
          <PatternLayout>
            <pattern>${patternMetrics}</pattern>
          </PatternLayout>
          <Policies>
            <SizeBasedTriggeringPolicy size="2 MB"/>
          </Policies>
          <DefaultRolloverStrategy max="9"/>
        </RollingFile>
      </appenders>
      <loggers>
        <root level="info">
          <appender-ref ref="A1"/>
          <appender-ref ref="Console"/>
        </root>
        <Logger name="org.apache.storm.metric.LoggingMetricsConsumer" level="info" additivity="false">
          <appender-ref ref="METRICS"/>
        </Logger>
        <Logger name="STDERR" level="INFO">
          <appender-ref ref="STDERR"/>
          <appender-ref ref="Console"/>
        </Logger>
        <Logger name="STDOUT" level="INFO">
          <appender-ref ref="STDOUT"/>
          <appender-ref ref="Console"/>
        </Logger>
      </loggers>
    </configuration>