{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-metrics
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: metrics-exporter
    {{- if .Values.metrics.datadog.enabled }}
    tags.datadoghq.com/env: {{ .Values.metrics.environment | quote }}
    tags.datadoghq.com/service: {{ .Values.metrics.serviceName | quote }}
    tags.datadoghq.com/version: {{ .Values.metrics.serviceVersion | quote }}
    {{- end }}
  annotations:
    {{- if .Values.metrics.prometheus.scrape }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.exporter.port | quote }}
    prometheus.io/path: {{ .Values.metrics.prometheus.path | quote }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.exporter.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: metrics-exporter
{{- end }}