{{- if and .Values.ui.enabled .Values.ui.ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-ui
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- if or .Values.ui.ingress.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.ui.ingress.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ui.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.ui.ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.ui.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.ui.ingress.hostname }}
    - host: {{ .Values.ui.ingress.hostname }}
      http:
        paths:
          {{- if .Values.ui.ingress.extraPaths }}
          {{- toYaml .Values.ui.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ui.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.ui.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-ui" (include "common.names.fullname" .)) "servicePort" "http" "context" $) | nindent 14 }}
    {{- end }}
    {{- range .Values.ui.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-ui" (include "common.names.fullname" $)) "servicePort" "http" "context" $) | nindent 14 }}
    {{- end }}
    {{- if .Values.ui.ingress.extraRules }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ui.ingress.extraRules "context" $) | nindent 4 }}
    {{- end }}
  {{- if or (and .Values.ui.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ui.ingress.annotations )) .Values.ui.ingress.selfSigned)) .Values.ui.ingress.extraTls }}
  tls:
    {{- if and .Values.ui.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ui.ingress.annotations )) .Values.ui.ingress.selfSigned) }}
    - hosts:
        - {{ .Values.ui.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ui.ingress.hostname }}
    {{- end }}
    {{- if .Values.ui.ingress.extraTls }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ui.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}