apiVersion: v1
kind: Pod
metadata:
  name: storm-debug
  namespace: storm-system
spec:
  containers:
  - name: storm
    image: storm:2.8.1
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    env:
    - name: STORM_CONF_DIR
      value: /conf
    - name: STORM_LOG_DIR
      value: /apache-storm/logs
    volumeMounts:
    - name: config
      mountPath: /conf
  volumes:
  - name: config
    configMap:
      name: test-storm-storm-kubernetes