apiVersion: batch/v1
kind: Job
metadata:
  name: nimbus-log-capture
  namespace: storm-system
spec:
  template:
    spec:
      containers:
      - name: log-capturer
        image: storm:2.8.1
        command:
        - /bin/bash
        - -c
        - |
          echo "Starting log capture job..."
          
          # Mount the same config as nimbus
          export STORM_CONF_DIR=/conf
          export STORM_LOG_DIR=/captured-logs
          export STORM_LOG_STDOUT=true
          export STORM_LOG_LEVEL=DEBUG
          
          # Create log directory
          mkdir -p /captured-logs
          
          # Try to run nimbus with verbose logging
          echo "=== Starting nimbus with debug logging ==="
          storm nimbus 2>&1 | tee /captured-logs/nimbus-startup.log &
          NIMBUS_PID=$!
          
          # Wait a bit for startup
          sleep 10
          
          # Check if it's still running
          if ps -p $NIMBUS_PID > /dev/null; then
            echo "Nimbus still running after 10 seconds"
          else
            echo "Nimbus exited, exit code: $?"
          fi
          
          # Show what we captured
          echo "=== Captured logs ==="
          cat /captured-logs/nimbus-startup.log || echo "No logs captured"
          
          echo "=== Checking for any error logs ==="
          find /apache-storm/logs -name "*.log" -type f 2>/dev/null | while read f; do
            echo "File: $f"
            tail -20 "$f"
          done
          
          # Keep the logs available
          echo "=== Logs captured to PVC ==="
          cp -r /captured-logs/* /data/ 2>/dev/null || true
          
          echo "Job complete"
        volumeMounts:
        - name: storm-config
          mountPath: /conf
        - name: nimbus-data
          mountPath: /data
        - name: captured-logs
          mountPath: /captured-logs
      restartPolicy: Never
      volumes:
      - name: storm-config
        configMap:
          name: rts-storm-cluster-storm-crd-cluster-config
      - name: nimbus-data
        persistentVolumeClaim:
          claimName: nimbus-data-rts-storm-cluster-storm-crd-cluster-nimbus-0
      - name: captured-logs
        emptyDir: {}