apiVersion: storm.apache.org/v1beta1
kind: StormTopology
metadata:
  name: wordcount-test
  namespace: storm-system
spec:
  clusterRef: storm-cluster
  topology:
    name: wordcount-test
    jar:
      url: https://repo1.maven.org/maven2/org/apache/storm/storm-starter/2.6.0/storm-starter-2.6.0.jar
    mainClass: org.apache.storm.starter.WordCountTopology
    args:
      - wordcount-test
    config:
      topology.workers: "2"
      topology.debug: "false"
  workers:
    replicas: 2
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"