apiVersion: storm.apache.org/v1beta1
kind: StormTopology
metadata:
  name: exclamation-topology
  namespace: storm-system
spec:
  clusterRef: storm-cluster
  topology:
    name: exclamation-topology
    jar:
      url: "https://repo1.maven.org/maven2/org/apache/storm/storm-starter/2.6.4/storm-starter-2.6.4.jar"
    mainClass: "org.apache.storm.starter.ExclamationTopology"
    config:
      "topology.workers": "1"
      "topology.version": "1.0.0"