apiVersion: storm.apache.org/v1beta1
kind: StormCluster
metadata:
  name: test-storm
  namespace: storm-system
spec:
  image:
    repository: apache/storm
    tag: "2.6.0"
    pullPolicy: IfNotPresent
  nimbus:
    replicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  supervisor:
    replicas: 3
    slotsPerSupervisor: 4
    deploymentMode: deployment
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
  ui:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  zookeeper:
    enabled: true
    replicas: 1
    persistence:
      enabled: false  # Disabled for testing
  config:
    storm.zookeeper.servers: '["test-storm-zookeeper"]'
    nimbus.seeds: '["test-storm-nimbus"]'
  metrics:
    enabled: true