apiVersion: storm.apache.org/v1beta1
kind: StormCluster
metadata:
  name: test-storm
  namespace: storm-system
spec:
  image:
    repository: apache/storm
    tag: "2.6.0"
  nimbus:
    replicas: 1
  supervisor:
    replicas: 2
    slotsPerSupervisor: 4
  ui:
    enabled: true
  zookeeper:
    enabled: true
    replicas: 1
  config:
    storm.zookeeper.servers: '["test-storm-zookeeper"]'
    nimbus.seeds: '["test-storm-nimbus"]'