apiVersion: storm.apache.org/v1beta1
kind: StormCluster
metadata:
  name: storm-cluster-storm-kubernetes
  namespace: storm-system
spec:
  image:
    repository: storm
    tag: "2.4.0"
  nimbus:
    replicas: 1
  supervisor:
    replicas: 2
    slotsPerSupervisor: 4
  ui:
    enabled: true
  zookeeper:
    enabled: true
    replicas: 1
  config:
    storm.zookeeper.servers: '["storm-cluster-zookeeper"]'
    nimbus.seeds: '["storm-cluster-storm-kubernetes-nimbus"]'