apiVersion: storm.apache.org/v1beta1
kind: StormCluster
metadata:
  name: storm-cluster-storm-kubernetes
  namespace: storm-system
spec:
  image:
    repository: apache/storm
    tag: "2.6.0"
  nimbus:
    replicas: 1
  supervisor:
    replicas: 3