apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storm-cluster-storm-kubernetes-topology-jars
  namespace: storm-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard