# WordCount topology example for testing
apiVersion: storm.apache.org/v1beta1
kind: StormTopology
metadata:
  name: wordcount-test
  namespace: storm-system
spec:
  clusterRef: storm-cluster
  topology:
    name: wordcount
    jar:
      url: https://repo1.maven.org/maven2/org/apache/storm/storm-starter/2.4.0/storm-starter-2.4.0.jar
    mainClass: org.apache.storm.starter.WordCountTopology
    config:
      topology.workers: "2"
      topology.debug: "false"
  workers:
    replicas: 2
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"