apiVersion: storm.apache.org/v1beta1
kind: StormTopology
metadata:
  name: simple-exclamation
  namespace: storm-system
spec:
  clusterRef: rts-storm-cluster-storm-crd-cluster
  topology:
    name: exclamation-topology
    jar:
      # Using public URL instead of container image
      url: "https://repo1.maven.org/maven2/org/apache/storm/storm-starter/2.8.1/storm-starter-2.8.1.jar"
    mainClass: "org.apache.storm.starter.ExclamationTopology"
    config:
      topology.version: "1.0.0"
      topology.workers: "1"
      topology.debug: "false"