apiVersion: v1
kind: ServiceAccount
metadata:
  name: storm-controller
  namespace: storm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storm-controller-role
rules:
# Storm CRDs
- apiGroups: ["storm.apache.org"]
  resources: ["stormclusters", "stormtopologies", "stormworkerpools"]
  verbs: ["*"]
- apiGroups: ["storm.apache.org"]
  resources: ["stormclusters/status", "stormtopologies/status", "stormworkerpools/status"]
  verbs: ["get", "patch", "update"]
# Core resources
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
# Leader election
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storm-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storm-controller-role
subjects:
- kind: ServiceAccount
  name: storm-controller
  namespace: storm-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storm-controller-custom
  namespace: storm-system
  labels:
    app.kubernetes.io/name: storm-controller-custom
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: storm-controller-custom
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: storm-controller-custom
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: storm-controller
      containers:
      - name: controller
        image: apache/storm-controller:latest
        imagePullPolicy: Never
        command:
        - /manager
        args:
        - --leader-elect
        - --storm-namespace=storm-system
        - --storm-cluster=storm-cluster-storm-kubernetes
        - --ui-host=storm-kubernetes-ui.storm-system.svc.cluster.local
        - --nimbus-host=storm-kubernetes-nimbus.storm-system.svc.cluster.local
        env:
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: storm-controller-custom-metrics
  namespace: storm-system
  labels:
    app.kubernetes.io/name: storm-controller-custom
    app.kubernetes.io/component: controller
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: storm-controller-custom
    app.kubernetes.io/component: controller