apiVersion: storm.apache.org/v1beta1
kind: StormTopology
metadata:
  name: wordcount-helm-test
  namespace: storm-system
spec:
  clusterRef: storm-cluster-storm-kubernetes
  topology:
    name: wordcount-helm
    jar:
      url: "https://repo1.maven.org/maven2/org/apache/storm/storm-starter/2.4.0/storm-starter-2.4.0.jar"
    mainClass: org.apache.storm.starter.WordCountTopology
    args:
    - "wordcount-helm"  # topology name argument
    config:
      topology.workers: "1"
      topology.max.spout.pending: "1000"
  workers:
    replicas: 1
  suspend: false