apiVersion: storm.apache.org/v1beta1
kind: StormTopology
metadata:
  name: wordcount-container
  namespace: storm-system
spec:
  clusterRef: test-cluster
  topology:
    name: wordcount-container
    jar:
      container:
        image: apache/storm:2.8.1
        path: /apache-storm/examples/storm-starter/storm-starter-topologies-2.8.1.jar
        extractionMode: job  # Options: job, initContainer, sidecar
    mainClass: "org.apache.storm.starter.WordCountTopology"
    config:
      topology.version: "1.0.0"
      topology.workers: "2"
      topology.debug: "false"
      topology.max.spout.pending: "1000"
      topology.message.timeout.secs: "60"