apiVersion: storm.apache.org/v1beta1
kind: StormTopology
metadata:
  name: wordcount-container-test
  namespace: storm-system
spec:
  clusterRef: storm-cluster-storm-kubernetes
  topology:
    name: wordcount-container
    jar:
      container:
        image: "ghcr.io/apache/storm-topology-example:latest"
        path: "/storm-starter.jar"
        pullPolicy: IfNotPresent
        extractionMode: "job"
    mainClass: org.apache.storm.starter.WordCountTopology
    args:
      - "wordcount-container"
    config:
      topology.workers: "1"
      topology.max.spout.pending: "500"