apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "storm-shared.fullname" . }}-operator-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "storm-shared.componentLabels" (dict "component" "controller" "context" .) | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  defaults.yaml: |
    defaults:
      # Default Storm configuration
      storm:
        image:
          registry: {{ include "storm-shared.images.registry" (dict "imageRoot" .Values.operator.defaults.storm.image "global" .Values.global) | quote }}
          repository: {{ .Values.operator.defaults.storm.image.repository | quote }}
          tag: {{ .Values.operator.defaults.storm.image.tag | quote }}
        config:
          {{- range $key, $value := .Values.operator.defaults.storm.config }}
          {{ $key }}: {{ $value | toJson }}
          {{- end }}
      # Default cluster sizing
      cluster:
        nimbus:
          replicas: {{ .Values.operator.defaults.cluster.nimbus.replicas }}
        supervisor:
          replicas: {{ .Values.operator.defaults.cluster.supervisor.replicas }}
          slotsPerSupervisor: {{ .Values.operator.defaults.cluster.supervisor.slots }}
        ui:
          enabled: {{ .Values.operator.defaults.cluster.ui.enabled }}
      # Default Zookeeper connection
      zookeeper:
        {{- if .Values.zookeeper.enabled }}
        servers:
          - "{{ include "storm-shared.fullname" . }}-zookeeper-headless:2181"
        {{- else if .Values.externalZookeeper.servers }}
        servers:
          {{- range .Values.externalZookeeper.servers }}
          - {{ . | quote }}
          {{- end }}
        {{- else }}
        servers: {{ .Values.operator.defaults.zookeeper.servers | toJson }}
        {{- end }}
        connectionTimeout: {{ .Values.operator.defaults.zookeeper.connectionTimeout }}
        sessionTimeout: {{ .Values.operator.defaults.zookeeper.sessionTimeout }}
  {{- if .Values.operator.configuration }}
  custom-config.yaml: |
    {{- .Values.operator.configuration | nindent 4 }}
  {{- end }}