apiVersion: v2
name: storm-kubernetes
description: Apache Storm is a distributed real-time computation system for Kubernetes
type: application
version: 0.1.0
appVersion: "2.8.1"
kubeVersion: ">=1.23.0-0"
home: https://storm.apache.org/
sources:
  - https://github.com/apache/storm
  - https://github.com/apache/storm/tree/master/charts/storm-kubernetes
maintainers:
  - name: Apache Storm Community
    email: dev@storm.apache.org
    url: https://storm.apache.org/
icon: https://storm.apache.org/images/logo.png
keywords:
  - storm
  - streaming
  - real-time
  - processing
  - apache
annotations:
  category: Analytics
  licenses: Apache-2.0
dependencies:
  - name: storm-shared
    version: "0.1.0"
    repository: "file://../storm-shared"