# Storm local development values

# Storm cluster configuration
cluster:
  enabled: true
  extraConfig:
    storm.log.level: "INFO"

# UI configuration
ui:
  enabled: true
  replicaCount: 1

# Nimbus configuration
nimbus:
  enabled: true
  replicaCount: 1

# Supervisor configuration  
supervisor:
  enabled: true
  replicaCount: 1
  slotsPerSupervisor: 1
  
  # Memory configuration - using auto mode for simplicity
  memoryConfig:
    mode: "auto"
    memoryPerWorker: "1Gi"      # 1GB per worker for local dev
    memoryOverheadPercent: 25    # 25% JVM overhead
    cpuPerWorker: "0.5"          # 0.5 CPU per worker for local dev

# Zookeeper configuration
zookeeper:
  enabled: true
  replicaCount: 3