# Storm local development values
# Optimized for local development with minimal resources

# Global image override for local development
global:
  imageRegistry: ""

# Storm cluster configuration
cluster:
  enabled: true
  # Configure cluster-wide settings via environment variables
  extraConfig:
    storm.log.level: "INFO"
    storm.zookeeper.session.timeout: 20000
    storm.zookeeper.connection.timeout: 15000

# UI configuration
ui:
  enabled: true
  replicaCount: 1
  # Override image for local development
  image:
    repository: storm-controller
    tag: local
    pullPolicy: Never
  # Use text logging for local development (easier to read)
  extraEnvVars:
    - name: LOG_FORMAT
      value: "text"
  # UI-specific configuration
  extraConfig:
    ui.childopts: "-Xmx768m"

# Nimbus configuration
nimbus:
  enabled: true
  replicaCount: 1
  # Override image for local development
  image:
    repository: storm-controller
    tag: local
    pullPolicy: Never
  # Use text logging for local development
  extraEnvVars:
    - name: LOG_FORMAT
      value: "text"
  # Nimbus-specific configuration
  extraConfig:
    nimbus.childopts: "-Xmx1024m"
    nimbus.task.timeout.secs: 30
    nimbus.supervisor.timeout.secs: 60

# Supervisor configuration  
supervisor:
  enabled: true
  replicaCount: 1
  # Override image for local development
  image:
    repository: storm-controller
    tag: local
    pullPolicy: Never
  slotsPerSupervisor: 4
  
  # Memory configuration - using auto mode for simplicity
  memoryConfig:
    mode: "auto"
    memoryPerWorker: "1Gi"      # 1GB per worker for local dev
    memoryOverheadPercent: 25    # 25% JVM overhead
    cpuPerWorker: "0.5"          # 0.5 CPU per worker for local dev
  
  # Use text logging for local development
  extraEnvVars:
    - name: LOG_FORMAT
      value: "text"
  
  # Supervisor-specific configuration
  extraConfig:
    supervisor.childopts: "-Xmx256m"
    supervisor.worker.timeout.secs: 30
    supervisor.worker.start.timeout.secs: 120

# Zookeeper configuration
zookeeper:
  enabled: true
  replicaCount: 3