# Storm deployment with node affinity and tolerations
# Example values for deploying Storm on dedicated nodes

# Inherit from local values
crd:
  install: true

controller:
  enabled: true
  image:
    repository: storm-controller
    tag: latest
    pullPolicy: Never
  nodeSelector:
    node: storm
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "storm"
    effect: "NoSchedule"

stormCluster:
  enabled: true
  name: storm-cluster

nimbus:
  replicas: 1
  nodeSelector:
    node: storm
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "storm"
    effect: "NoSchedule"

supervisor:
  replicas: 1
  slotsPerSupervisor: 1
  nodeSelector:
    node: storm
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "storm"
    effect: "NoSchedule"

ui:
  enabled: true
  nodeSelector:
    node: storm
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "storm"
    effect: "NoSchedule"

zookeeper:
  replicas: 3
  # Bitnami Zookeeper chart supports nodeSelector and tolerations
  nodeSelector:
    node: storm
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "storm"
    effect: "NoSchedule"

storm:
  config:
    storm.log.level: "INFO"