# Storm local development values

# Storm cluster configuration
nimbus:
  replicas: 1

supervisor:
  replicas: 1
  slotsPerSupervisor: 1

ui:
  enabled: true

zookeeper:
  replicas: 3
  
# Enable debug logging
storm:
  config:
    storm.log.level: "INFO"