# Local development values for Storm Helm chart

# Override the image to use the official Storm image
image:
  registry: docker.io
  repository: storm
  tag: latest
  pullPolicy: IfNotPresent

# Use a single Nimbus instance for local development
nimbus:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: false  # Disable persistence for local development

# Reduce supervisor count and resources
supervisor:
  replicaCount: 2
  slotsPerSupervisor: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

# UI configuration
ui:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  # Enable simple auth for testing
  auth:
    enabled: true
    type: simple
    users:
      - username: admin
        password: admin123

# Controller configuration
controller:
  enabled: false  # Disable controller for now - needs custom image
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Zookeeper configuration (minimal for local)
zookeeper:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  persistence:
    enabled: false

# Disable resource-intensive features for local development
metrics:
  enabled: true
  serviceMonitor:
    enabled: false  # Disable unless Prometheus Operator is installed
  prometheusRule:
    enabled: false