# Values for deploying Storm with controller enabled
# This extends the local development values

# Include base local values
# Use a single Nimbus instance for local development
nimbus:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: false  # Disable persistence for local development

# Reduce supervisor count and resources
supervisor:
  replicaCount: 2
  slotsPerSupervisor: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

# UI configuration
ui:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

# Controller configuration - ENABLED with custom image
controller:
  enabled: true
  image:
    # Using the locally built image
    repository: storm-controller
    tag: latest
    pullPolicy: Never  # Use local image
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # Enable Thrift client
  extraEnvVars:
    - name: STORM_USE_THRIFT
      value: "true"
    - name: STORM_THRIFT_CONNECTION_TIMEOUT
      value: "30000"
    - name: STORM_THRIFT_MAX_POOL_SIZE
      value: "10"

# Zookeeper configuration (minimal for local)
zookeeper:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  persistence:
    enabled: false

# Storm image configuration
image:
  registry: docker.io
  repository: storm
  tag: latest
  pullPolicy: IfNotPresent

# Enable CRDs
crds:
  install: true
  keep: true

# Disable resource-intensive features for local development
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: false