{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "storm-shared.fullname" . }}-operator
  labels:
    {{- include "storm-shared.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "storm-shared.fullname" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ include "storm-shared.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}