apiVersion: v1
kind: ServiceAccount
metadata:
  name: storm-controller
  namespace: storm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storm-controller-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: ["storm.apache.org"]
  resources: ["stormclusters", "stormtopologies", "stormworkerpools"]
  verbs: ["*"]
- apiGroups: ["storm.apache.org"]
  resources: ["stormclusters/status", "stormtopologies/status", "stormworkerpools/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["storm.apache.org"]
  resources: ["stormclusters/finalizers", "stormtopologies/finalizers", "stormworkerpools/finalizers"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storm-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storm-controller-role
subjects:
- kind: ServiceAccount
  name: storm-controller
  namespace: storm-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storm-controller
  namespace: storm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storm-controller
  template:
    metadata:
      labels:
        app: storm-controller
    spec:
      serviceAccountName: storm-controller
      containers:
      - name: manager
        image: storm-controller:test
        imagePullPolicy: Never
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi