---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storm.apache.org
  resources:
  - stormclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storm.apache.org
  resources:
  - stormclusters/finalizers
  verbs:
  - update
- apiGroups:
  - storm.apache.org
  resources:
  - stormclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storm.apache.org
  resources:
  - stormtopologies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storm.apache.org
  resources:
  - stormtopologies/finalizers
  verbs:
  - update
- apiGroups:
  - storm.apache.org
  resources:
  - stormtopologies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storm.apache.org
  resources:
  - stormworkerpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storm.apache.org
  resources:
  - stormworkerpools/finalizers
  verbs:
  - update
- apiGroups:
  - storm.apache.org
  resources:
  - stormworkerpools/status
  verbs:
  - get
  - patch
  - update
