---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storm-controller
  namespace: storm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storm-controller-role
rules:
# Storm CRDs
- apiGroups: ["storm.apache.org"]
  resources: ["stormclusters", "stormtopologies", "stormworkerpools"]
  verbs: ["*"]
- apiGroups: ["storm.apache.org"]
  resources: ["stormclusters/status", "stormtopologies/status", "stormworkerpools/status"]
  verbs: ["get", "patch", "update"]
# Core resources
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
# Leader election
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storm-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storm-controller-role
subjects:
- kind: ServiceAccount
  name: storm-controller
  namespace: storm-system