---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storm-controller
  namespace: storm-system
  labels:
    app.kubernetes.io/name: storm-controller
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: storm-controller
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: storm-controller
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: storm-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: controller
        image: apache/storm-controller:latest
        imagePullPolicy: Never  # Using local image for testing
        command:
        - /manager
        args:
        - --leader-elect
        - --storm-namespace=storm-system
        env:
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: STORM_CLUSTER_NAME
          value: "storm-cluster"
        - name: LOG_LEVEL
          value: "info"
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: storm-controller-metrics
  namespace: storm-system
  labels:
    app.kubernetes.io/name: storm-controller
    app.kubernetes.io/component: controller
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: storm-controller
    app.kubernetes.io/component: controller