name: CI

on:
  push:
    branches: [ main, feature/storm-controller ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: veteranchad/storm-controller
  GO_VERSION: '1.23'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        working-directory: src
        run: |
          make test
          
      - name: Run vet
        working-directory: src
        run: |
          make vet

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./src/cover.out
          flags: unittests
          name: codecov-umbrella

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: src
          args: --timeout=5m --out-format=colored-line-number


  build-controller-images:
    name: Build Controller Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        storm-version: ["2.8.1"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            VERSION=main
          else
            VERSION=pr-${{ github.event.pull_request.number }}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "storm_tag=$VERSION-storm${{ matrix.storm-version }}" >> $GITHUB_OUTPUT

      - name: Build and push controller image
        uses: docker/build-push-action@v5
        with:
          context: src
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            STORM_VERSION=${{ matrix.storm-version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.storm_tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:storm${{ matrix.storm-version }}
          # GitHub Actions cache disabled due to intermittent 502 errors
          # See KNOWN_ISSUES.md for details
          # cache-from: type=gha,scope=buildkit
          # cache-to: type=gha,mode=max,scope=buildkit
          labels: |
            org.opencontainers.image.title=Storm Controller
            org.opencontainers.image.description=Kubernetes controller for Apache Storm
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.storm.version=${{ matrix.storm-version }}

  build-default-image:
    name: Build Default Image
    runs-on: ubuntu-latest
    needs: [test, lint]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            VERSION=main
          else
            VERSION=pr-${{ github.event.pull_request.number }}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push controller image
        uses: docker/build-push-action@v5
        with:
          context: src
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # GitHub Actions cache disabled due to intermittent 502 errors
          # See KNOWN_ISSUES.md for details
          # cache-from: type=gha,scope=buildkit
          # cache-to: type=gha,mode=max,scope=buildkit
          labels: |
            org.opencontainers.image.title=Storm Controller
            org.opencontainers.image.description=Kubernetes controller for Apache Storm
            org.opencontainers.image.version=${{ steps.version.outputs.version }}

  lint-helm-chart:
    name: Lint Storm Kubernetes Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Build Helm dependencies
        run: |
          helm dependency update charts/storm-kubernetes

      - name: Lint chart
        run: |
          helm lint charts/storm-kubernetes --strict
          
      - name: Validate values schema
        run: |
          helm lint charts/storm-kubernetes --strict --values charts/storm-kubernetes/values-production.yaml
          
  test-helm-chart:
    name: Test Storm Kubernetes Chart
    runs-on: ubuntu-latest
    needs: [lint-helm-chart]
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Build dependencies
        run: |
          helm dependency update charts/storm-kubernetes
          
      - name: Test default installation
        run: |
          helm template test-release charts/storm-kubernetes > /tmp/default.yaml
          echo "✓ Default installation template generated successfully"
          
      - name: Test with security features
        run: |
          helm template test-release charts/storm-kubernetes \
            --values charts/storm-kubernetes/values-production-security.yaml > /tmp/security.yaml
          echo "✓ Security features template generated successfully"
          
      - name: Test with monitoring
        run: |
          helm template test-release charts/storm-kubernetes \
            --values charts/storm-kubernetes/values-production-monitoring.yaml > /tmp/monitoring.yaml || \
          (echo "Failed to generate monitoring template" && exit 1)
          echo "✓ Monitoring features template generated successfully"
          
      - name: Test with HPA
        run: |
          helm template test-release charts/storm-kubernetes \
            --values charts/storm-kubernetes/values-production-hpa.yaml > /tmp/hpa.yaml
          echo "✓ HPA features template generated successfully"
          
      - name: Test with authentication
        run: |
          helm template test-release charts/storm-kubernetes \
            --values charts/storm-kubernetes/values-production-auth.yaml > /tmp/auth.yaml
          echo "✓ Authentication features template generated successfully"
          
      - name: Test full production setup
        run: |
          helm template test-release charts/storm-kubernetes \
            --values charts/storm-kubernetes/values-production.yaml > /tmp/production.yaml
          echo "✓ Full production template generated successfully"
          
      - name: Validate generated manifests
        run: |
          # Check that key resources are generated
          echo "Checking for required resources..."
          grep -q "kind: StatefulSet" /tmp/production.yaml && echo "✓ StatefulSet found" || echo "✗ StatefulSet missing"
          grep -q "kind: Deployment" /tmp/production.yaml && echo "✓ Deployment found" || echo "✗ Deployment missing"
          grep -q "kind: Service" /tmp/production.yaml && echo "✓ Service found" || echo "✗ Service missing"
          grep -q "kind: ConfigMap" /tmp/production.yaml && echo "✓ ConfigMap found" || echo "✗ ConfigMap missing"
          grep -q "kind: ServiceAccount" /tmp/production.yaml && echo "✓ ServiceAccount found" || echo "✗ ServiceAccount missing"
          grep -q "kind: NetworkPolicy" /tmp/production.yaml && echo "✓ NetworkPolicy found" || echo "✗ NetworkPolicy missing"
          grep -q "kind: PodDisruptionBudget" /tmp/production.yaml && echo "✓ PodDisruptionBudget found" || echo "✗ PodDisruptionBudget missing"
          grep -q "kind: ServiceMonitor" /tmp/monitoring.yaml && echo "✓ ServiceMonitor found" || true
          grep -q "kind: HorizontalPodAutoscaler" /tmp/hpa.yaml && echo "✓ HPA found" || echo "✗ HPA missing"
          grep -q "storm-auth" /tmp/auth.yaml && echo "✓ Auth ConfigMap found" || echo "✗ Auth ConfigMap missing"

  package-helm-chart:
    name: Package Storm Kubernetes Chart
    runs-on: ubuntu-latest
    needs: [lint-helm-chart, test-helm-chart]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Determine version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=0.0.0-$(git rev-parse --short HEAD)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub Registry for Helm
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login registry-1.docker.io --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build dependencies
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For PRs, remove lock files and update dependencies
            rm -f charts/storm-kubernetes/Chart.lock
          fi
          
          # Always update dependencies to ensure consistency
          helm dependency update charts/storm-kubernetes
          
      - name: Update chart versions
        run: |
          VERSION=${{ steps.version.outputs.version }}
          sed -i "s/version: .*/version: ${VERSION}/" charts/storm-kubernetes/Chart.yaml
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            sed -i "s/appVersion: .*/appVersion: ${GITHUB_REF#refs/tags/}/" charts/storm-kubernetes/Chart.yaml
          fi

      - name: Package charts
        run: |
          mkdir -p .cr-release-packages
          helm package charts/storm-kubernetes --destination .cr-release-packages

      - name: Upload chart artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-charts
          path: .cr-release-packages/*.tgz

      - name: Log in to Docker Hub Registry
        if: github.event_name != 'pull_request'
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login registry-1.docker.io --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push to OCI registry
        if: github.event_name != 'pull_request'
        run: |
          for chart in .cr-release-packages/*.tgz; do
            helm push $chart oci://registry-1.docker.io/veteranchad
          done


  generate-manifests:
    name: Generate Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate manifests
        working-directory: src
        run: |
          make manifests
          make generate

      - name: Check for uncommitted changes
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "ERROR: Uncommitted changes after code generation. Please run 'make manifests generate' and commit."
            git status -s
            exit 1
          fi

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'