name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GO_VERSION: '1.23'

jobs:

  build-container-images:
    name: Build Multi-Platform Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        storm-version: ["2.8.1"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Determine version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "storm_tag=$VERSION-storm${{ matrix.storm-version }}" >> $GITHUB_OUTPUT

      - name: Build and push controller image
        uses: docker/build-push-action@v5
        with:
          context: src
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            STORM_VERSION=${{ matrix.storm-version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.storm_tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:storm${{ matrix.storm-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-default-image:
    name: Build Default Image
    runs-on: ubuntu-latest
    needs: [build-container-images]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Determine version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push controller image (default)
        uses: docker/build-push-action@v5
        with:
          context: src
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release-helm-charts:
    name: Release Helm Charts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Update chart versions
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          APP_VERSION=${GITHUB_REF#refs/tags/}
          
          for chart in storm-operator storm-crd-cluster storm-kubernetes storm-shared; do
            sed -i "s/version: .*/version: ${VERSION}/" charts/$chart/Chart.yaml
            sed -i "s/appVersion: .*/appVersion: ${APP_VERSION}/" charts/$chart/Chart.yaml
          done

      - name: Build dependencies
        run: |
          helm dependency build charts/storm-operator
          helm dependency build charts/storm-kubernetes

      - name: Package charts
        run: |
          mkdir -p .release
          for chart in storm-operator storm-crd-cluster storm-kubernetes storm-shared; do
            helm package charts/$chart --destination .release
          done

      - name: Create chart index
        run: |
          helm repo index .release --url https://github.com/${{ github.repository }}/releases/download/${GITHUB_REF#refs/tags/}

      - name: Upload chart artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-charts
          path: |
            .release/*.tgz
            .release/index.yaml

      - name: Log in to Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin

      - name: Push to OCI registry
        run: |
          for chart in .release/*.tgz; do
            helm push $chart oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
          done


  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-default-image, release-helm-charts]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate release notes
        id: notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          cat > release-notes.md << 'EOF'
          ## Storm Controller ${VERSION}
          
          ### Installation
          
          #### Using Helm (Recommended)
          
          ```bash
          # Add the Helm repository
          helm repo add storm-controller https://github.com/${{ github.repository }}/releases/download/${VERSION}
          helm repo update
          
          # Install the Storm Operator
          helm install storm-operator storm-controller/storm-operator \
            --namespace storm-operator --create-namespace
          
          # Deploy a Storm cluster using CRDs
          helm install my-cluster storm-controller/storm-crd-cluster \
            --namespace storm-prod --create-namespace
          ```
          
          #### Using OCI Registry
          
          ```bash
          # Install Storm Operator
          helm install storm-operator oci://ghcr.io/${{ github.repository_owner }}/charts/storm-operator \
            --version ${VERSION#v} \
            --namespace storm-operator --create-namespace
          ```
          
          ### Container Images
          
          Controller images with Storm 2.8.1:
          - `ghcr.io/${{ github.repository }}:${VERSION}` (Storm 2.8.1)
          - `ghcr.io/${{ github.repository }}:storm2.8.1`
          
          ### Helm Charts
          
          | Chart | Version | Description |
          |-------|---------|-------------|
          | storm-operator | ${VERSION#v} | Storm Operator with optional Zookeeper |
          | storm-crd-cluster | ${VERSION#v} | Deploy Storm cluster via CRD |
          | storm-kubernetes | ${VERSION#v} | Traditional Helm deployment |
          | storm-shared | ${VERSION#v} | Shared templates and helpers |
          
          ### What's Changed
          
          EOF
          
          if [ -n "$PREV_TAG" ]; then
            echo "#### Commits since $PREV_TAG" >> release-notes.md
            echo "" >> release-notes.md
            git log --pretty=format:"- %s (%an)" ${PREV_TAG}..HEAD >> release-notes.md
          else
            echo "#### All Commits" >> release-notes.md
            echo "" >> release-notes.md
            git log --pretty=format:"- %s (%an)" --max-count=20 >> release-notes.md
          fi
          
          cat >> release-notes.md << 'EOF'
          
          ### Upgrading
          
          #### From v0.x to ${VERSION}
          
          1. Update CRDs:
             ```bash
             kubectl apply -f https://github.com/${{ github.repository }}/releases/download/${VERSION}/storm-crds.yaml
             ```
          
          2. Upgrade the operator:
             ```bash
             helm upgrade storm-operator storm-controller/storm-operator \
               --namespace storm-operator \
               --version ${VERSION#v}
             ```
          
          ### Documentation
          
          - [Getting Started](https://github.com/${{ github.repository }}/blob/${VERSION}/README.md)
          - [Helm Chart Documentation](https://github.com/${{ github.repository }}/tree/${VERSION}/charts)
          - [Monitoring Guide](https://github.com/${{ github.repository }}/blob/${VERSION}/monitoring/README.md)
          - [Examples](https://github.com/${{ github.repository }}/tree/${VERSION}/examples)
          
          EOF

      - name: Create CRD manifest
        working-directory: src
        run: |
          make manifests
          cp config/crd/bases/*.yaml ../artifacts/
          cd ../artifacts
          cat storm.apache.org_*.yaml > storm-crds.yaml

      - name: Prepare release assets
        run: |
          cd artifacts
          mv helm-charts/*.tgz .
          mv helm-charts/index.yaml .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-notes.md
          draft: false
          prerelease: ${{ contains(github.ref, '-rc.') || contains(github.ref, '-beta.') || contains(github.ref, '-alpha.') }}
          generate_release_notes: true
          files: |
            artifacts/*.tgz
            artifacts/index.yaml
            artifacts/storm-crds.yaml